/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "mitro_api_constants.h"

namespace mitro_api {

const mitro_apiConstants g_mitro_api_constants;

mitro_apiConstants::mitro_apiConstants() {
}

} // namespace

