/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mitro_api_CONSTANTS_H
#define mitro_api_CONSTANTS_H

#include "mitro_api_types.h"

namespace mitro_api {

class mitro_apiConstants {
 public:
  mitro_apiConstants();

};

extern const mitro_apiConstants g_mitro_api_constants;

} // namespace

#endif
